require('plugin-setups/nvim-tree')
require('plugin-setups/nvim-lspconfig')
require('plugin-setups/onedark')
require('plugin-setups/nvim-treesitter')
require('plugin-setups/autocompletion')
require('plugin-setups/null-ls')
require('plugin-setups/nvim-telescope')
